version: '3'
services:
  headlamp:
    image: ghcr.io/kinvolk/headlamp:v0.13.0
    command: ["--kubeconfig","/headlamp/config/config", "--port","64446"]
    restart: unless-stopped
    volumes:
      - ~/.kube/:/headlamp/config:ro
    ports:
      - 64446:64446
