name: Trigger Headlamp website update

# See https://github.com/headlamp-k8s/headlamp-website
on:
  push:
    paths:
      - 'docs/**'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  trigger_flatpak_update:
    name: Trigger Headlamp website update
    runs-on: ubuntu-latest
    steps:
      - name: Trigger via gh
        env:
          GITHUB_TOKEN: ${{ secrets.KINVOLK_REPOS_TOKEN }}
        run: |
          gh api repos/flathub/io.kinvolk.Headlamp/dispatches --raw-field event_type=headlamp-docs-update
